import javax.swing.JOptionPane;

/**
 * Currency Converter 
 * Program converts currencies from USD to EUR to GBP (P. 11.25)
 * @author Khalid Diriye
 */
public class CurrencyConvertGUI extends javax.swing.JFrame {

    private static final double EUR_TO_USD = 1.420;
    private static final double GBP_TO_USD = 1.630;
    private static final double GBP_TO_EUR = 1.130;

    /**
     * Creates new form CurrencyConvertGUI
     */
    public CurrencyConvertGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FirstComboBox = new javax.swing.JComboBox();
        SecondComboBox = new javax.swing.JComboBox();
        convert_text_box = new javax.swing.JTextField();
        from_Label = new javax.swing.JLabel();
        to_Label = new javax.swing.JLabel();
        ConvertButton = new javax.swing.JButton();
        converted_Label = new javax.swing.JLabel();
        converted_value_title_label = new javax.swing.JLabel();
        input_label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        FirstComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "EUR", "GBP" }));

        SecondComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "USD", "EUR", "GBP" }));

        from_Label.setText(" From:");

        to_Label.setText(" To:");

        ConvertButton.setText("Convert");
        ConvertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConvertButtonActionPerformed(evt);
            }
        });

        converted_Label.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        converted_Label.setText("... ");
        converted_Label.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        converted_value_title_label.setText("Converted Value: ");

        input_label.setText(" Input:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ConvertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(converted_value_title_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(converted_Label))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_label)
                    .addComponent(FirstComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SecondComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(from_Label)
                    .addComponent(to_Label))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(convert_text_box)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(from_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FirstComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(input_label)
                .addGap(2, 2, 2)
                .addComponent(convert_text_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(to_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SecondComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ConvertButton, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(converted_Label)
                        .addComponent(converted_value_title_label))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * This method handles the Convert Button action that converts the
     * currencies to their correct values
     * @param evt
     */
    private void ConvertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConvertButtonActionPerformed

        double user_input = 0;
        user_input = Double.parseDouble(convert_text_box.getText()); // Get text input from text box and assign to double

        //Checks text box if value is a positive number otherwise print error message
        try {
            user_input = Double.parseDouble(convert_text_box.getText());
            if (user_input < 0) {
                throw new IllegalArgumentException();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: Currency cannot be negative",
                    "Invalid currency amount", JOptionPane.ERROR_MESSAGE);
        }

        if (FirstComboBox.getSelectedIndex() == 1 && SecondComboBox.getSelectedIndex() == 0) { //From: EUR To: USD
            double output_EUR_TO_USD = user_input * EUR_TO_USD;
            converted_Label.setText(String.format("%.2f", output_EUR_TO_USD));
        }
        if (FirstComboBox.getSelectedIndex() == 1 && SecondComboBox.getSelectedIndex() == 2) { //From: EUR To: GBP
            double output_EUR_TO_GBP = user_input / GBP_TO_EUR;
            converted_Label.setText(String.format("%.2f", output_EUR_TO_GBP));
        }
        if (FirstComboBox.getSelectedIndex() == 0 && SecondComboBox.getSelectedIndex() == 1) { //From: USD To: EUR
            double output_USD_TO_EUR = user_input / EUR_TO_USD;
            converted_Label.setText(String.format("%.2f", output_USD_TO_EUR));
        }
        if (FirstComboBox.getSelectedIndex() == 0 && SecondComboBox.getSelectedIndex() == 2) { //From: USD To: GBP
            double output_USD_TO_GBP = user_input / GBP_TO_USD;
            converted_Label.setText(String.format("%.2f", output_USD_TO_GBP));
        }
        if (FirstComboBox.getSelectedIndex() == 2 && SecondComboBox.getSelectedIndex() == 0) { //From: GBP To: USD
            double output_GBP_TO_USD = user_input * GBP_TO_USD;
            converted_Label.setText(String.format("%.2f", output_GBP_TO_USD));
        }
        if (FirstComboBox.getSelectedIndex() == 2 && SecondComboBox.getSelectedIndex() == 1) { //From: GBP To: EUR
            double output_GBP_TO_EUR = user_input * GBP_TO_EUR;
            converted_Label.setText(String.format("%.2f", output_GBP_TO_EUR));
        }
        if (FirstComboBox.getSelectedItem() == SecondComboBox.getSelectedItem()) { //From: Same To: Same display message
            converted_Label.setText(String.valueOf(user_input)); //Value assigned as same value
            JOptionPane.showMessageDialog(null, "Error: Currency selections are the same",
                    "Warning", JOptionPane.ERROR_MESSAGE);
        }
        else {
            //Do nothing
        }
    }

    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CurrencyConvertGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CurrencyConvertGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ConvertButton;
    private javax.swing.JComboBox FirstComboBox;
    private javax.swing.JComboBox SecondComboBox;
    private javax.swing.JTextField convert_text_box;
    private javax.swing.JLabel converted_Label;
    private javax.swing.JLabel converted_value_title_label;
    private javax.swing.JLabel from_Label;
    private javax.swing.JLabel input_label;
    private javax.swing.JLabel to_Label;
    // End of variables declaration//GEN-END:variables

}
