--Question 1

SELECT TEAM_NAME
FROM TEAM
WHERE TEAM_NAME BETWEEN 'Fuschia' AND 'Yellow';

--Question 2

SELECT ANIM_NAME, ANIM_GENDER
FROM ANIMAL
WHERE ANIM_ARRIVAL_DATE = '15-MAY-08';

--Question 3

SELECT P.PRODUCT_ID,PRODUCT_NAME
FROM PRODUCT P  JOIN MANUFACTURED_PRODUCT MP ON P.PRODUCT_ID = MP.PRODUCT_ID
WHERE MOD(MP.PRODUCT_ID,2)=0;

--Question 4

SELECT MAINT_TITLE
FROM MAINTENANCE
GROUP BY MAINT_TITLE
HAVING COUNT(*) > 1;

--Question 5

SELECT DISTINCT OFFICE_BUILDING
FROM OFFICE;

--Question 6 

SELECT PRODUCT_ID,PRODUCT_NAME
FROM PRODUCT JOIN MANUFACTURED_PRODUCT USING (PRODUCT_ID)
WHERE PRODUCT_FINISH_DATE BETWEEN '1-APR-2007' AND '30-APR-2007';

--Question 7

SELECT CAST (AVG(EMP_SALARY) AS NUMERIC(36,2)) AS AVERAGE_EMP_SALARY
FROM EMPLOYEE;

--Question 8 

SELECT MAX(SELLING_PRICE)
FROM RECEIPT_LINE;

--Question 9

SELECT EMP_FIRST_NAME, EMP_LAST_NAME
FROM EMPLOYEE
WHERE EMP_SALARY > (SELECT AVG(EMP_SALARY) FROM EMPLOYEE);

--Question 10

SELECT PAY_AMOUNT
FROM PAYMENT
WHERE PAY_AMOUNT = (SELECT MAX(PAY_AMOUNT) FROM PAYMENT);

--Question 11 

SELECT MIN(INVEN_AMOUNT) AS SMALLEST_INVENTORY, MAX(INVEN_MAX_STOCK) AS LARGEST_INVENTORY, CAST (AVG(INVEN_REORDER_POINT) AS NUMERIC(36,0)) AS AVERAGE_INVENTORY
FROM INVENTORY;

--Question 12

SELECT VET_HOSPITAL , COUNT(VET_ID) AS NUMBER_OF_VETS_THAT_WORK
FROM VET
GROUP BY VET_HOSPITAL;

--Question 13

SELECT STORE_ID, SUM(TRANS_TOTAL_AMT) AS TRANSCATION_TOTALS
FROM STORE 
JOIN TRANSACTION USING (STORE_ID)
GROUP BY STORE_ID;
              
--Question 14 

SELECT PRIV_EVEN_TYPE, SUM(PAY_AMOUNT) AS TOTAL_EVENT_PRICE
FROM PRIVATE_EVENT 
JOIN PRIVATE_EVENT_PAYMENT USING(PRIV_EVEN_ID)
JOIN PAYMENT USING (PAY_ID)
GROUP BY PRIV_EVEN_TYPE;

--Question 15

SELECT ANIM_NAME, COUNT(ANIM_NAME)
FROM ANIMAL
WHERE ANIM_NAME LIKE 'K%'
GROUP BY ANIM_NAME;

--Question 16

SELECT PAY_CREDIT_CARD_TYPE , SUM(PAY_AMOUNT)
FROM PAYMENT
WHERE PAY_TYPE = 'Credit Card' AND PAY_CREDIT_CARD_TYPE IS NOT NULL
GROUP BY PAY_CREDIT_CARD_TYPE;

--Question 17

SELECT OFFICE_BUILDING, COUNT(OFFICE_ID) AS OFFICES
FROM OFFICE
GROUP BY OFFICE_BUILDING;

--Question 18

SELECT ILL_DESCRIPTION,ILLD
FROM (SELECT ILL_DESCRIPTION , COUNT(ANIM_ID) AS ILLD
FROM ILLNESS_TYPE JOIN ILLNESS USING (ILL_TYPE_ID)
GROUP BY ILL_DESCRIPTION)
WHERE ILLD >= 6;

--Question 19

SELECT S.STORE_ID, T.TRANS_TOTAL_AMT
FROM STORE S
JOIN TRANSACTION T
ON S.STORE_ID = T.STORE_ID;

--Question 20

SELECT SPON_COMPANY_NAME
FROM CORPORATE_SPONSOR
WHERE SPON_DATE_DONATED BETWEEN '1-MAR-07' AND '31-AUG-08'
ORDER BY SPON_COMPANY_NAME;

--Question 21

SELECT DISTINCT FOOD_SUP_COMPANY_NAME
FROM FOOD_SUPPLIER FS
JOIN FOOD_ITEM_SUPPLIER FIS
ON FIS.FOOD_SUP_ID = FS.FOOD_SUP_ID
WHERE FIS.FOOD_ITEM_ID = '112'
OR FIS.FOOD_ITEM_ID = '22';

--Question 22

SELECT D.DEPT_ID, D.DEPT_NAME, O.OFFICE_ID, O.OFFICE_BUILDING, EMP_FIRST_NAME, EMP_LAST_NAME
FROM EMPLOYEE E, DEPARTMENT D, OFFICE O
WHERE E.DEPT_ID = D.DEPT_ID AND E.OFFICE_ID = O.OFFICE_ID  AND EMP_ID = 4703;

--Question 23

SELECT EMP_FIRST_NAME, EMP_LAST_NAME, O.OFFICE_BUILDING, D.DEPT_NAME
FROM EMPLOYEE E, DEPARTMENT D, OFFICE O 
WHERE E.OFFICE_ID = O.OFFICE_ID 
AND E.DEPT_ID = D.DEPT_ID;

--Question 24

SELECT P.PRODUCT_NAME, P.PRODUCT_TYPE, PP.PRODUCT_PURCHASE_PRICE, MP.PRODUCT_FINISH_DATE
FROM PRODUCT P, PURCHASED_PRODUCT PP, MANUFACTURED_PRODUCT MP
WHERE P.PRODUCT_ID = PP.PRODUCT_ID
AND P.PRODUCT_ID = MP.PRODUCT_ID;

--Question 25

SELECT A.ANIM_NAME, FI.FOOD_ITEM_DESCRIPTION
FROM ANIMAL A, ANIMAL_DIETARY_REQUIREMENTS AD, FOOD_ITEM FI, ANIMAL_BREED AB
WHERE A.ANIM_ID= AD.ANIM_ID AND 
FI.FOOD_ITEM_ID = AD.FOOD_ITEM_ID AND
A.ANIM_BREED_ID = AB.ANIM_BREED_ID
AND ANIM_BREED_NAME = 'Ring-tailed Lemur';

SELECT ANIM_NAME, FOOD_ITEM_DESCRIPTION
FROM ANIMAL JOIN ANIMAL_DIETARY_REQUIREMENTS USING (ANIM_ID) JOIN FOOD_ITEM USING (FOOD_ITEM_ID)
JOIN FOOD_CATEGORY USING (FOOD_CATEGORY_ID)
WHERE FOOD_CATEGORY_DESCRIPTION LIKE 'Ring-tailed Lemur%';


--Question 26

SELECT ANIM_NAME, ANIM_BREED_NAME, ANIM_DIETARY_REQUIREMENTS, ANIM_CHECKUP_DATE
FROM ANIMAL JOIN ANIMAL_BREED USING (ANIM_BREED_ID)
JOIN ANIMAL_DIETARY_REQUIREMENTS USING (ANIM_ID)
JOIN ANIMAL_CHECKUP USING (ANIM_ID)
WHERE ANIM_CHECKUP_DATE LIKE '%04' 
AND ANIM_BREED_NAME IN ('Lion','Caribou');

--Question 27

SELECT I.ILL_TYPE_ID, ILL_DESCRIPTION, ANIM_NAME, ANIM_BREED_NAME, ANIM_LIVING_ENVIRONMENT_TYPE
FROM ILLNESS_TYPE I 
JOIN ILLNESS T 
ON T.ILL_TYPE_ID= I.ILL_TYPE_ID
JOIN ANIMAL USING (ANIM_ID)
JOIN ANIMAL_BREED USING (ANIM_BREED_ID)
JOIN ANIMAL_LIVING_ENVIRONMENT USING (ANIM_LIVING_ENVIRONMENT_ID)
WHERE ANIM_NAME LIKE 'J%'
ORDER BY ANIM_NAME;

--Question 28

SELECT PAY_TYPE
FROM (SELECT PAY_TYPE, SUM (PAY_AMOUNT) AS AMOUNT
FROM PAYMENT
GROUP BY PAY_TYPE)
WHERE AMOUNT = (SELECT MAX (AMOUNT)
FROM(SELECT PAY_TYPE, SUM (PAY_AMOUNT) AS AMOUNT
FROM PAYMENT
GROUP BY PAY_TYPE));

--Question 29

SELECT S.STORE_ID, S.STORE_ADDRESS
FROM STORE S
WHERE ZOO_ID = (SELECT ZOO_ID FROM ZOO WHERE ZOO_ID = '1002');

--Question 30

SELECT PRODUCT_NAME
FROM PRODUCT 
WHERE PRODUCT_ID IN 
(SELECT PRODUCT_ID FROM PURCHASED_PRODUCT 
WHERE PRODUCT_PURCHASE_PRICE > 5.37);



